config/routes.rb
Rails.application.routes.draw do

  root 'recipes#index'

  get 'recipes/search' => 'recipes#search'

  get 'recipes/list' => 'recipes#list'

  resources :ingredients

  resources :recipes

  resources :groups

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :recipes, :through => :recipeGroups
  has_many :recipeGroups
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipes, :through => :recipeIngredients
  has_many :recipeIngredients
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, :through => :recipeIngredients
  has_many :groups, :through => :recipeGroups
  has_many :recipeIngredients
  has_many :recipeGroups

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  accepts_nested_attributes_for :recipeIngredients,
           :reject_if => :all_blank,
           :allow_destroy => true
  accepts_nested_attributes_for :ingredients
end

app/models/recipe_group.rb
class RecipeGroup < ActiveRecord::Base
  #self.table_name = "recipe_ingredients"
  belongs_to :group
  belongs_to :recipe
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  #self.table_name = "recipe_ingredients"
  belongs_to :ingredient
  belongs_to :recipe

  accepts_nested_attributes_for :ingredient,
                                :reject_if => :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :fetch_nav

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:success] = "Your Group was created succesfully"
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  private
    def fetch_nav
      @groups = Group.select("id","name")
      @ingredients = Ingredient.all
    end

    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :fetch_nav
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Your Ingredient was created succesfully"
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  private
    def fetch_nav
      @groups = Group.select("id","name")
      @ingredients = Ingredient.all
    end

    def ingredient_params
      params.require(:ingredient).permit(:name)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :fetch_nav
  before_action :authenticate, :only => [:new, :edit, :list]

  def index
    if params[:ing]
      ingredient = Ingredient.find(params[:ing])
      @recipes = ingredient.recipes.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
    elsif params[:grp]
      group = Group.find(params[:grp])
      @recipes = group.recipes.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
    else
      @recipes = Recipe.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def list
    @recipes = Recipe.all.order('updated_at DESC')
  end

  def new
    @recipe = Recipe.new
    @all_ingredients = Ingredient.all
    @recipe_ingredient = @recipe.recipeIngredients.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    params[:recipe][:id].each  do |ingredient|
      if !ingredient.empty?
        @recipe.recipeIngredients.build(:id)
      end
    end
    if @recipe.save
      flash[:success] = "Your recipe was created succesfully"
      redirect_to recipes_list_path
    else
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      redirect_to recipes_list_path
      # Handle a successful update.
    else
      render :edit
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def search
    if params[:search].empty?
        @recipes = Recipe.all.order('created_at DESC')
        return @recipes
    end
    terms = params[:search].split
    terms.each do |term|
       @recipes = @recipes.to_a.concat Recipe.where("lower(search_terms) LIKE '%#{term}%' or lower(name) LIKE '%#{term}%'
                          or description LIKE '%#{term}%'").order('updated_at DESC')
    end
  end

  private
    def fetch_nav
      @groups = Group.select("id","name")
      @ingredients = Ingredient.all
    end

    def recipe_params
      params.require(:recipe).permit(:name, :summary, :url, :description, :search_terms, :image, recipeIngredient_attributes: [ingredient_attributes: [:id, :name]])
    end

    def authenticate
      authenticate_or_request_with_http_basic do |username,password|
        username == "admin" && password == "password"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
end

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/index.html.erb
<div class="box">
  <ol>
  <% @groups.each do |group| %>
    <li><%= group.name%></li>
  <%end%>
</ol>
</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <p>
      <h1>Create a new Group</h1>
    </p>
    <%= form_for @group do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit 'Create Group', class: "btn btn-success" %>
    <%end%>
  </div>
</div>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/index.html.erb
<div class="box">
  <ol>
  <% @ingredients.each do |ingredient| %>
    <li><%= ingredient.name%></li>
  <%end%>
</ol>
</div>

app/views/ingredients/new.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <p>
      <h1>Create a new Ingredient</h1>
    </p>
    <%= form_for @ingredient do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit 'Create Ingredient', class: "btn btn-success" %>
    <%end%>
  </div>
</div>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crockpot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Business Casual - Start Bootstrap Theme</title>

  <!-- Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%=OORConstant.facebook_app_id%>";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <script src="https://apis.google.com/js/platform.js"></script>
  <div class="container banner-container">
    <img class="img-responsive" src="/assets/banner.png" alt="Chania" width="100%" height="auto">
  </div>
  <!-- Navigation -->
  <%= render "partials/navbar" %>
  <div class="container">
    <div class="col-sm-9">
      <%= yield %>
    </div>
    <div class="col-sm-3">
      <%= render 'partials/sidebar' %>
    </div>
  </div>
  <%= render "partials/footer" %>
</body>
</html>

app/views/partials/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <p>Copyright &copy; Indian Crock-Pot Cookery 2014</p>
            </div>
        </div>
    </div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="#" role="button">Home <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "Home", recipes_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
          <ul class="dropdown-menu multi-level" role="menu">
            <% @ingredients.each do |ingredient| %>
            <li class="dropdown-submenu">
                <%= link_to ingredient.name, recipes_path(:ing => ingredient) %>
                <ul class="dropdown-menu">
                  <% ingredient.recipes.each do |recipe| %>
                    <li><%= link_to recipe.name, recipe_path(recipe)%></li>
                  <%end%>
                </ul>
                <li role="separator" class="divider"></li>
            </li>
            <%end%>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">I'm hungry for<span class="caret"></span></a>
          <ul class="dropdown-menu multi-level" role="menu">
            <% @groups.each do |group| %>
              <li><%= link_to group.name, recipes_path(:grp => group) %></li>
              <li role="separator" class="divider"></li>
            <%end%>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right form-inline">
          <%= form_tag(recipes_search_path, :method => "get", id: "search-form", html: {class: 'navbar-form'}) do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Recipes", size: "35", class: "form-control pull-left" %>
            <%= link_to "", recipes_search_path(params[:search]), {:class => "btn btn-default glyphicon glyphicon-search pull-right"} %>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_sidebar.html.erb
<div class="box">
    <div class="fb-page" data-href="https://www.facebook.com/indiancrockpotcookery" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/indiancrockpotcookery"><a href="https://www.facebook.com/indiancrockpotcookery">Indian Crock-Pot Recipes</a></blockquote></div></div>
    </br>
    </br>
    <div class="social-likes">
      <div class="facebook" title="Share link on Facebook">Facebook</div>
      <div class="pinterest" data-media="http://example.com/image/url.jpg">Pinterest</div>
    </div>

</div>

app/views/partials/_social_section.html.erb
<div class="fb-like" data-href="https://www.facebook.com/indiancrockpotcookery" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
<div class="g-ytsubscribe" data-channel="indiancrockpot" data-layout="default" data-count="default"></div>

app/views/recipes/_recipe.html.erb
<div class="row">
    <div class="box">
            <div class="col-lg-12">
              <div class="date">Posted on
                <strong><%=recipe.created_at.strftime("%b %d, %Y")%></strong>
              </div>
              <h2>
                <strong><%= link_to recipe.name, recipe_path(recipe) %></strong>
              </h2>
              <p><%= recipe.summary %></p>
                <div class="col-lg-7 col-centered">
                  <div class="video-container">
                    <%= embed('https://www.youtube.com/watch?v=4AH3mIwHWeo') %>
                  </div>
                </div>
              <p><%= h(recipe.description).gsub(/\n/, '<br/>').html_safe %></p>
            </div>
    </div>
</div>

app/views/recipes/_recipeGroup_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">

    <%= f.fields_for :group do |quantity_group| %>
      <%= quantity_group.text_field :name %>
    <% end %>

  </div>
</li>

app/views/recipes/_recipeIngredient_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">

    <%= f.fields_for :ingredient do |quantity_ingredient| %>
      <%= quantity_ingredient.text_field :name %>
    <% end %>

  </div>
</li>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/edit.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <p>
      <h1>Create a new Recipe</h1>
    </p>
    <%= form_for @recipe do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :summary %>
      <%= f.text_field :summary %>

      <%= f.label :url %>
      <%= f.text_field :url %>

      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>

      <%= f.label :search_terms %>
      <%= f.text_field :search_terms %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      </br>
        <fieldset id="recipe-ingredients">
          <%= f.label :ingredients %>
          <ol>
            <%= f.fields_for :recipeIngredients do |quantity| %>
              <%= render 'recipeIngredient_fields', f: quantity %>
            <% end %>
          </ol>
          <%= link_to_add_association 'add ingredient', f, :recipeIngredients,
            'data-association-insertion-node' => "#recipe-ingredients ol",
            'data-association-insertion-method' => "append",
            :wrap_object => Proc.new {|quantity| quantity.build_ingredient; quantity } %>
      </fieldset>
    </br>
      <fieldset id="recipe-groups">
        <%= f.label :groups %>
        <ol>
          <%= f.fields_for :recipeGroups do |quantity| %>
            <%= render 'recipeGroup_fields', f: quantity %>
          <% end %>
        </ol>
        <%= link_to_add_association 'add group', f, :recipeGroups,
          'data-association-insertion-node' => "#recipe-groups ol",
          'data-association-insertion-method' => "append",
          :wrap_object => Proc.new {|quantity| quantity.build_group; quantity } %>
        </fieldset>

      <%= f.submit 'Create Recipe', class: "btn btn-success" %>
    <%end%>
  </div>
</div>

app/views/recipes/index.html.erb
<div id="recipes">
  <%= render @recipes %>
</div>
<%= will_paginate @recipes %>

app/views/recipes/index.js.erb
$('#recipes').append('<%= escape_javascript render(@recipes) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@recipes) %>');

app/views/recipes/list.html.erb
<div class="row">
    <div class="box">
      <% @recipes.each do |recipe| %>
      <div class="col-lg-12">
        <div class="well">
            <strong><%= link_to recipe.name, edit_recipe_path(recipe) %></strong>
            <p>
              <%= recipe.summary %>
            </p>
        </div>
      </div>
      <%end%>
    </div>
</div>

app/views/recipes/new.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <p>
      <h1>Create a new Recipe</h1>
    </p>
    <%= form_for @recipe do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :summary %>
      <%= f.text_field :summary %>

      <%= f.label :url %>
      <%= f.text_field :url %>

      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>

      <%= f.label :search_terms %>
      <%= f.text_field :search_terms %>

      <%= f.label :image %>
      <%= f.file_field :image %>


      <%= f.fields_for(@recipe_ingredient) do |ri| %>
          <%= collection_select(:recipe, :id, @all_ingredients, :id, :name, {}, {:multiple => true})%>
      <% end %>

  </br>


      <%= f.submit 'Create Recipe', class: "btn btn-success" %>
    <%end%>
  </div>
</div>

app/views/recipes/search.html.erb
<div class="row text-center">
  <div id="gallery" class="box">
  <% @recipes.each do |recipe| %>
    <div class="col-xs-6 col-sm-4">
      <div class="cliente">
      <%= link_to image_tag(recipe.image.url), recipe_path(recipe) %>
    </br>
      <%= link_to recipe.name, recipe_path(recipe) %>
    </div>
    </div>
  <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<%= render :partial => "recipe", :locals => {:recipe => @recipe} %>